name: anp4nlg
channels:
  - defaults
  - conda-forge
dependencies:
  - fairseq
  - sacremoses
  - pytorch
  - wandb
  - gensim
  - pip:
    - tensorboard
    - tqdm
    - tokenizers
    - subword-nmt
