name: anp4nlg_gpu
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python
  - pip
  - cudatoolkit=11.3.1
  - pytorch
  - fairseq
  - sacremoses
  - wandb
  - pip:
    - tensorboard
    - tqdm